kitchen/urls.py
from django.urls import path
from django.views.generic import TemplateView

from kitchen.views import (
    index,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    AssignUserToDishView,
    CustomLoginView,
)


app_name = "kitchen"

urlpatterns = [
    path("", index, name="index"),
    path(
        "dish-types/",
        DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish-types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path(
        "dishes/<int:pk>/toggle-assign/",
        AssignUserToDishView.as_view(),
        name="dish-assign"),
    path("login/", CustomLoginView.as_view(), name='login'),
    path(
        "sign-in/",
        TemplateView.as_view(template_name='kitchen/sign-in.html'),
        name='sign-in'),
]

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

from kitchen.views import signup

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("signup/", signup, name="signup"),
]

templates/includes/footer-auth.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
      <div class="container">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-12 col-md-6 my-auto">
            <div class="copyright text-center text-sm text-white text-lg-start">
              &copy; AppKitchen
            </div>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer-components.html
  <!-- -------- START FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->
  <footer class="footer py-5">
    <div class="container">
      <div class="row">
        <div class="col-8 mx-auto text-center mt-1">
          <p class="mb-0 text-secondary">
            AppKitchen.
          </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- -------- END FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->

templates/includes/footer.html
<footer class="footer pt-5 mt-5">
  <div class="container">
    <div class=" row">
      <div class="col-md-6 mb-4 ms-auto">
        <div>
          <img src="{{ ASSETS_ROOT }}/img/logo-food.png" class="mb-3 footer-logo" alt="main_logo">
          <h6 class="font-weight-bolder mb-4">Kitchen</h6>
        </div>
      </div>
      <div class="col-12">
        <div class="text-center">
          <p class="text-dark my-4 text-sm font-weight-normal">
            &copy; AppKitchen.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation-transparent.html
  <!-- Navbar Transparent -->
  <nav class="navbar navbar-expand-lg position-absolute top-0 z-index-3 w-100 shadow-none my-3  navbar-transparent ">
    <div class="container">
      <a class="navbar-brand  text-white " href="{% url 'kitchen:index' %}" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
        Kitchen service
      </a>
      <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon mt-2">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </span>
      </button>
      <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
        <ul class="navbar-nav navbar-nav-hover ms-auto">

          {% if request.user.is_authenticated %}

            <li class="nav-item dropdown dropdown-hover mx-2 ms-lg-6">
              <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" id="dropdownMenuPages8" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                Navigations
                <img src="{{ ASSETS_ROOT }}/img/down-arrow-white.svg" alt="down-arrow" class="arrow ms-2 d-lg-block d-none">
                <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-2 d-lg-none d-block">
              </a>
              <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-lg mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages8">
                <div class="d-none d-lg-block">
                  <a href="{% url 'kitchen:cook-list' %}" class="dropdown-item border-radius-md">
                    <span>Cooks</span>
                  </a>
                  <a href="{% url 'kitchen:dish-list' %}" class="dropdown-item border-radius-md">
                    <span>Dishes</span>
                  </a>
                  <a href="{% url 'kitchen:dish-type-list' %}" class="dropdown-item border-radius-md">
                    <span>Dish Types</span>
                  </a>
                  <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                    Account
                  </h6>
                  <a href="{% url 'login' %}" class="dropdown-item border-radius-md">
                    <span>Sign In</span>
                  </a>
                </div>
              </div>
            </li>

          {% endif %}
        
          
          {% if request.user.is_authenticated %}
            <li class="nav-item ms-lg-auto">
              <form method="post" action="{% url 'logout' %}" class="nav-link nav-link-icon me-2">
                <i class="fa fa-sign-out me-1"></i>
                {% csrf_token %}
                <button class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</button>
              </form>
            </li>          
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->

templates/includes/navigation.html
  <!-- Navbar -->
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid px-0">
            <div class="navbar-brand font-weight-bolder ms-sm-3">
              Restaurant Kitchen service
            </div>
            <div class="navbar-brand font-weight-bolder ms-sm-3">
              Customer: <span class="text-muted">{{ user.username }}</span>
            </div>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-auto">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                    Navigations
                    <img src="{{ ASSETS_ROOT }}/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                  </a>
                  <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                    <div class="d-none d-lg-block">
                      <a href="{% url 'kitchen:cook-list' %}" class="dropdown-item border-radius-md">
                        <span>Cooks</span>
                      </a>
                      <a href="{% url 'kitchen:dish-list' %}" class="dropdown-item border-radius-md">
                        <span>Dishes</span>
                      </a>
                      <a href="{% url 'kitchen:dish-type-list' %}" class="dropdown-item border-radius-md">
                        <span>Dish Types</span>
                      </a>
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                        Account
                      </h6>
                      <a href="{% url 'login' %}" class="dropdown-item border-radius-md">
                        <span>Sign In</span>
                      </a>
                    </div>
                  </div>
                </li>

                {% if request.user.is_authenticated %}
                  <li class="nav-item ms-lg-auto">
                  <form method="post" action="{% url 'logout' %}" class="nav-link nav-link-icon me-2">
                    <i class="fa fa-sign-out me-1"></i>
                    {% csrf_token %}
                    <button class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</button>
                  </form>
                  </li>          
                {% endif %}

              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <div class="container">
    <div class="row justify-space-between py-2">
      <div class="col-lg-4 mx-auto">
        <ul class="pagination pagination-primary pagination-lg m-2">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" aria-label="Previous" href="?{% query_transform request page=page_obj.previous_page_number %}">
              <span aria-hidden="true"><i class="material-icons" aria-hidden="true">chevron_left</i></span>
              </a>
            </li>
          {% endif %}
          <li class="page-item active"><span class="page-link">{{ page_obj.number }}</span></li>
          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" aria-label="Next" href="?{% query_transform request page=page_obj.next_page_number %}">
                <span aria-hidden="true"><i class="material-icons" aria-hidden="true">chevron_right</i></span>
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
{% endif %}

<style>
  .pagination-lg .page-link {
    font-size: 1.25rem; /* Increase font size */
    padding: 0.75rem 1.5rem; /* Increase padding */
  }
  .pagination-lg .material-icons {
    font-size: 1.5rem; /* Increase icon size */
  }
</style>

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">
      User: {{ user.username }}
    </li>
    <form method="post" action="{% url 'logout' %}" class="list-group-item">
      {% csrf_token %}
      <button type="submit">Logout</button>
    </form>
  {% else %}
    <li class="list-group-item">
    <a href="{% url 'login' %}">Login</a>
    </li>
  {% endif %}
  <li class="list-group-item">
    <a href="{% url 'kitchen:index' %}">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'kitchen:cook-list' %}">All cooks</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'kitchen:dish-list' %}">All dishes</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'kitchen:dish-type-list' %}">All dish-types</a>
  </li>
</ul>