kitchen/urls.py
from django.urls import path
from django.views.generic import TemplateView

from kitchen.views import (
    index,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    AssignUserToDishView,
    CustomLoginView,
)


app_name = "kitchen"

urlpatterns = [
    path("", index, name="index"),
    path(
        "dish-types/",
        DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish-types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path(
        "dishes/<int:pk>/toggle-assign/",
        AssignUserToDishView.as_view(),
        name="dish-assign"),
    path("login/", CustomLoginView.as_view(), name='login'),
    path(
        "sign-in/",
        TemplateView.as_view(template_name='kitchen/sign-in.html'),
        name='sign-in'),
]

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

from kitchen.views import signup

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("signup/", signup, name="signup"),
]

kitchen/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=False, default=0)

    class Meta:
        ordering = ("username", )
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.CASCADE,
        related_name="dishes"
    )
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes"
    )

    class Meta:
        ordering = ("name", )
        verbose_name = "dish"
        verbose_name_plural = "dishes"

    def __str__(self):
        return f"{self.name}: {self.dish_type} ({self.price})"

    def get_absolute_url(self):
        return reverse("kitchen:dish-detail", kwargs={"pk": self.pk})


kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from kitchen.models import Cook, Dish


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = (UserCreationForm.Meta.fields +
                  ("first_name", "last_name", "years_of_experience",))


class CookUpdateExperience(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ("years_of_experience", )


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishTypeNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label=False,
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class CookUsernameSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label=False,
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username"}
        )
    )


class DishNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label=False,
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username*",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email*",
                "class": "form-control"
            }
        ))
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "First Name",
                "class": "form-control"
            }
        ), required=False)
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Last Name",
                "class": "form-control"
            }
        ), required=False)
    years_of_experience = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                "placeholder": "Years of Experience",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password*",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check*",
                "class": "form-control"
            }
        ))

    class Meta:
        model = Cook
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
            "years_of_experience",
        )


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))

kitchen/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import (
    CookCreationForm,
    CookUpdateExperience,
    DishForm,
    DishTypeNameSearchForm,
    CookUsernameSearchForm,
    DishNameSearchForm,
    SignUpForm, LoginForm,
)
from kitchen.models import Cook, Dish, DishType


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_cook = Cook.objects.count()
    num_dish = Dish.objects.count()
    num_dish_types = DishType.objects.count()
    context = {
        "num_cook": num_cook,
        "num_dish": num_dish,
        "num_dish_types": num_dish_types,
    }
    return render(request, "kitchen/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "kitchen/dish_type_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form"] = DishTypeNameSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypeNameSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_confirm_delete.html"


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("name")
        context["search_form"] = CookUsernameSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CookUsernameSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.all().prefetch_related("dishes__dish_type")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateExperience


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form"] = DishNameSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Dish.objects.all().select_related("dish_type")
        form = DishNameSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


class AssignUserToDishView(LoginRequiredMixin, generic.View):
    @staticmethod
    def post(request, pk):
        dish = Dish.objects.get(pk=pk)
        if request.user not in dish.cooks.all():
            dish.cooks.add(request.user)
        else:
            dish.cooks.remove(request.user)
        return HttpResponseRedirect(
            reverse_lazy("kitchen:dish-detail", kwargs={"pk": pk})
    )


class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = "registration/login.html"


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("kitchen:index")
    else:
        form = SignUpForm()
    return render(request, "registration/signup.html", {"form": form})

templates/kitchen/cook_detail.html
{#{% extends "base.html" %}#}
{##}
{#{% block content %}#}
{#  <h1>#}
{#    Username: {{ cook.username }}#}
{#    <a href="{% url 'kitchen:cook-update' pk=cook.id %}" class="btn btn-secondary link-to-page">#}
{#      Update#}
{#    </a>#}
{#    #}
{#    <a href="{% url 'kitchen:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page">#}
{#      Delete#}
{#    </a>#}
{#  </h1>#}
{##}
{#  <p><strong>First name:</strong> {{ cook.first_name }}</p>#}
{#  <p><strong>Last name:</strong> {{ cook.last_name }}</p>#}
{#  <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>#}
{##}
{##}
{#  <hr>#}
{#  <div class="ml-3">#}
{#    <h5>Dishes prepared by the chef: </h5>#}
{#    <ul>#}
{#      {% for dish in cook.dishes.all  %}#}
{#          <li>{{ dish.name }} ({{ dish.dish_type }})</li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#  </div>#}
{#{% endblock %}#}

{% extends "layouts/base.html" %}

{% block title %} About Cook {% endblock %}

{% block body_class %} blog-author {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation-transparent.html' %}

  <header>
    <div class="page-header min-height-400" style="background-image: url('{{ ASSETS_ROOT }}/img/city-profile.jpg');" loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <!-- START Testimonials w/ user image & text & info -->
    <section class="py-sm-7 py-5 position-relative">
      <div class="container">
        <div class="row">
          <div class="col-12 mx-auto">
            <div class="mt-n8 mt-md-n9 text-center">
              <img class="avatar avatar-xxl shadow-xl position-relative z-index-2" src="{{ ASSETS_ROOT }}/img/logo-food-detail.png" alt="bruce" loading="lazy">
            </div>
            <div class="row py-5">
              <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mx-auto">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <h3 class="mb-0">{{ cook.first_name }} {{ cook.last_name }}</h3>
                  <div class="d-block">
                    <button type="button" class="btn btn-sm btn-outline-info text-nowrap mb-0">
                      <a href="{% url 'kitchen:cook-update' pk=cook.id %}">Edit</a>
                    </button>
                    <button type="button" class="btn btn-sm btn-outline-danger text-nowrap mb-0">
                      <a href="{% url 'kitchen:cook-delete' pk=cook.id %}">Delete</a>
                    </button>
                  </div>
                </div>
                <div class="row mb-4">
                  <div class="col-auto">
                    <span class="h6">Username: </span>
                    <span>{{ cook.username }}</span>
                  </div>
                  <div class="col-auto">
                    <span class="h6">Years of experience: </span>
                    <span>{{ cook.years_of_experience }}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="py-3">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h3 class="mb-5">Dishes prepared by the chef:</h3>
          </div>
        </div>
        <div class="row">
          <div class="card card-plain">
            <ul>
              {% for dish in cook.dishes.all %}
                <li>
                  <h5> 
                    {{ dish.name }}
                  </h5>
                </li>
                <p class="text-muted">
                  Dish type: {{ dish.dish_type }}
                </p>
              {% empty %}
                <p>No dishes!</p>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </section>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/kitchen/dish_detail.html
{#{% extends "base.html" %}#}
{##}
{#{% block content %}#}
{#  <h1>Dish name: </h1>#}
{#    <h4>#}
{#      <em>{{ dish.name }}</em>#}
{#      <a #}
{#          href="{% url 'kitchen:dish-update' pk=dish.id %}"#}
{#      >Edit#}
{#      </a>#}
{#      #}
{#    </h4>#}
{#  <p><strong>Price: </strong>{{ dish.price }}</p>#}
{#  <p><strong>Description: </strong>{{ dish.description }}</p>#}
{#  <p style="color: red">If you want to delete this dish#}
{#    <a#}
{#        href="{% url 'kitchen:dish-delete' pk=dish.id %}"#}
{#        class="btn btn-danger"#}
{#    >CLick#}
{#    </a>#}
{#  </p>#}
{#  <div class="ml-3">#}
{#    <h3>A list of cooks to prepare the dish: </h3>#}
{#    {% for cook in dish.cooks.all %}#}
{#      <hr>#}
{#      <p class="text-muted">id: {{ cook.id }}</p>#}
{#      <p>{{ cook.first_name }} {{ cook.last_name }}#}
{#      {% if cook.years_of_experience %}#}
{#        ({{ cook.years_of_experience }} years of experience)#}
{#      {% endif %}#}
{#      </p>#}
{#    {% empty %}#}
{#      <p>No cooks!</p>#}
{#    {% endfor %}#}
{#  </div>#}
{#  {% if request.user in dish.cooks.all %}#}
{#    <form action="{% url 'kitchen:dish-assign' pk=dish.id %}" method="post">#}
{#    {% csrf_token %}#}
{#      <input type="submit" class="btn btn-danger link-to-page" value="Delete me from this dish">#}
{#    </form>#}
{#    {% else %}#}
{#    <form action="{% url 'kitchen:dish-assign' pk=dish.id %}" method="post">#}
{#    {% csrf_token %}#}
{#      <input type="submit" class="btn btn-success link-to-page" value="Assign me to this dish">#}
{#    </form>#}
{#  {% endif %}#}

{#{% endblock %}#}

{% extends "layouts/base.html" %}

{% block title %} About Dish {% endblock %}

{% block body_class %} blog-author {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation-transparent.html' %}

  <header>
    <div class="page-header min-height-400" style="background-image: url('{{ ASSETS_ROOT }}/img/city-profile.jpg');" loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <!-- START Testimonials w/ user image & text & info -->
    <section class="py-sm-7 py-5 position-relative">
      <div class="container">
        <div class="row">
          <div class="col-12 mx-auto">
            <div class="mt-n8 mt-md-n9 text-center">
              <img class="avatar avatar-xxl shadow-xl position-relative z-index-2" src="{{ ASSETS_ROOT }}/img/logo-food-detail.png" alt="bruce" loading="lazy">
            </div>
            <div class="row py-5">
              <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mx-auto">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <h3 class="mb-0">{{ dish.name }}</h3>
                  <div class="d-block">
                    <button type="button" class="btn btn-sm btn-outline-info text-nowrap mb-0">
                      <a href="{% url 'kitchen:dish-update' pk=dish.id %}">Edit</a>
                    </button>
                    <button type="button" class="btn btn-sm btn-outline-danger text-nowrap mb-0">
                      <a href="{% url 'kitchen:dish-delete' pk=dish.id %}">Delete</a>
                    </button>
                  </div>
                </div>
                <div class="row mb-4">
                  <div class="col-auto">
                    <span class="h6">Price: </span>
                    <span>{{ dish.price }}</span>
                  </div>
                </div>
                <p class="text-lg mb-0">
                  {{ dish.description }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="py-3">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h3 class="mb-5">A list of cooks to prepare the dish:</h3>
          </div>
        </div>
        <div class="row">
          <div class="card card-plain">
            {% for cook in dish.cooks.all %}
              <h5> Cook Name:
                <a class="text-dark font-weight-bold">{{ cook.first_name }} {{ cook.last_name }}
                  {% if user == cook %} (Me)
                  {% endif %}
                </a>
              </h5>
              <p class="text-muted">id: {{ cook.id }}
              {% if cook.years_of_experience %}
                ({{ cook.years_of_experience }} years of experience)
              {% endif %}
              </p>
            {% empty %}
              <p>No cooks!</p>
            {% endfor %}
          {% if request.user in dish.cooks.all %}
            <form action="{% url 'kitchen:dish-assign' pk=dish.id %}" method="post">
              {% csrf_token %}
              <input type="submit" class="btn btn-danger link-to-page" value="Delete me from this dish">
            </form>
          {% else %}
            <form action="{% url 'kitchen:dish-assign' pk=dish.id %}" method="post">
              {% csrf_token %}
              <input type="submit" class="btn btn-success link-to-page" value="Assign me to this dish">
            </form>
          {% endif %}
          </div>
        </div>
      </div>
    </section>
  </div>
  
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/kitchen/dish_type_list.html
{#{% extends "base.html" %}#}
{#{% load crispy_forms_filters %}#}
{##}
{#{% block title %}#}
{#  <title>Dish Type</title>#}
{#{% endblock %}#}
{##}
{#{% block content %}#}
{#  <h1>#}
{#    Dish Type List#}
{#    <a href="{% url 'kitchen:dish-type-create' %}" class="btn btn-primary link-to-page">#}
{#      Create#}
{#    </a>#}
{#  </h1>#}
{#  <form action="" method="get" class="form-inline">#}
{#    {{ search_form|crispy }}#}
{#    <input type="submit" value="🔎" class="btn btn-secondary">#}
{#  </form>#}
{#  {% if dish_type_list %}#}
{#    <table class="table">#}
{#      <tr>#}
{#        <th>ID</th>#}
{#        <th>Name</th>#}
{#        <th>Update</th>#}
{#        <th>Delete</th>#}
{#      </tr>#}
{##}
{#      {% for dish_type in dish_type_list %}#}
{#        <tr>#}
{#          <td>#}
{#            {{ dish_type.id }}#}
{#          </td>#}
{#          <td>#}
{#            {{ dish_type.name }}#}
{#          </td>#}
{#          <td>#}
{#            <a href="{% url 'kitchen:dish-type-update' pk=dish_type.id %}">#}
{#                Update#}
{#              </a>#}
{#          </td>#}
{#          <td>#}
{#            <a style="color: red"#}
{#                href="{% url 'kitchen:dish-type-delete' pk=dish_type.id %}">#}
{#                Delete#}
{#              </a>#}
{#          </td>#}
{#        </tr>#}
{#      {% endfor %}#}
{#    </table>#}
{##}
{#   {% else %}#}
{#      <p>There are no dish types in restaurant kitchen!</p>#}
{#  {% endif %}#}
{#{% endblock %}#}

{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block title %} About Dish Types {% endblock %}

{% block body_class %} about-us {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation-transparent.html' %}

  <header class="bg-gradient-dark">
    <div class="page-header min-vh-75" style="background-image: url('{{ ASSETS_ROOT }}/img/bg9.jpg');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">Type list of all dishes in our kitchen</h1>
                <a href="{% url 'kitchen:dish-type-create' %}" class="btn bg-gradient-light w-auto me-2">
                  Create new dish type
                </a>
            <div class="d-flex justify-content-center">
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="card card-body shadow-xl mx-3 mx-md-4 mt-n6">
  <section class="pb-5 position-relative bg-gradient-dark mx-n3">
    <div class="container">
      <div class="row">
        <div class="col-md-8 text-start mb-5 mt-5">
          <h3 class="text-white z-index-1 position-relative">You can see the whole list of dish types</h3>
        </div>
      </div>
      <div class="container">
        <div class="row justify-space-between py-2">
          <div class="col-lg-4 ">
            <div class="input-group input-group-dynamic">
              <form action="" method="get" class="form-inline">
                {{ search_form|crispy }}
                <input type="submit" value="🔎" class="btn btn-outline-white">
              </form>
            </div>
          </div>
        </div>
      </div>
      {% if dish_type_list %}
        <div class="row">
          {% for dish_type in dish_type_list %}
            <div class="col-lg-6 col-12">
              <div class="card card-profile mt-4">
                <div class="row">
                  <div class="col-12 my-auto">
                    <div class="card-body">
                      <h5 class="mb-0">{{ dish_type.name }}</h5>
                        <h6 class="text-muted">id: {{ dish_type.id }}</h6>
                      <p class="mb-0">
                        <button type="button" class="btn bg-gradient-light w-auto me-2">
                          <a href="{% url 'kitchen:dish-type-update' pk=dish_type.id %}">Update</a>
                        </button>
                        <button type="button" class="btn bg-gradient-danger w-auto me-2">
                          <a href="{% url 'kitchen:dish-type-delete' pk=dish_type.id %}">
                          Delete
                          </a>
                        </button>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      {% else %}
        <p>There are no dishes in restaurant kitchen!</p>
      {% endif %}
    </div>
  </section>
  </div>

{% endblock content %}